name: "🐛Bug Report / バグレポート"
description: Create a report to help us improve / 私達の改善を手助けするレポートを書いてください。
title: "[Bug]: "
labels: "bug"
body:
  - type: dropdown
    id: package
    attributes:
      label: "📦 Package / パッケージ"
      description: Select the package you are reporting the bug for / バグを報告するパッケージを選択してください。
      options:
        - spear-cli
        - create-spear
        - cms-js-core
        - plugin/i18n
        - plugin/seo
        - plugin/markdown
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "📝 Issue Description / 問題の説明"
      description: Describe the bug / バグについて説明してください。
      placeholder: Description of your Issue / 問題点を記載
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "🤔 Expected Behavior / 期待結果"
      description: A clear and concise description of what you expected to happen. / 想定する期待結果を明確に記載してください。
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: "👀 Current Behavior / 現在の動き"
      description: Please describe what the current behavior is / 今の動作を記載してください。.
      placeholder: But instead, on this page I'm noticing . . . 
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: 🖥️ Browser / ブラウザ
      description: Paste the result of [What's My Browser result](https://www.whatsmybrowser.org/). / [What's My Browser result](https://www.whatsmybrowser.org/)の結果を貼り付けてください。
      placeholder: E.g., https://www.whatsmybrowser.org/b/01V6Z
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: "📄 Additional Information"
      description: Add any other context about the problem here. / 問題について追加情報があれば記載してください。
    validations:
      required: false
